CREATE TABLE IF NOT EXISTS TutorRequests (
    requestID INT AUTO_INCREMENT PRIMARY KEY,
    userID INT NOT NULL,
    tutorID VARCHAR(50) NOT NULL,
    status ENUM('Pending', 'Approved', 'Rejected') DEFAULT 'Pending',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (userID) REFERENCES Users(userID),
    FOREIGN KEY (tutorID) REFERENCES Tutors(tutorID)
); 